version: 2

sources: 
- name: raw
  database: just-student-475409-a2
  schema: gz_raw_data
  loader: bigquery
  description: Gz_raw data set 
  freshness:
    warn_after: {count: 12, period: hour}
    error_after: {count: 24, period: hour}
  tables:
    -  name: sales
       identifier: raw_gz_sales
       description: sales of Greenweez 
       columns:
          - name: orders_id
            description: column
            tests:
              - not_null          
       tests: 
        - unique:
            column_name: "(orders_id || '-' || pdt_id)"

      
    - name: ship
      identifier: raw_gz_ship
      description: Ship of Greenweez
      columns:
         - name: orders_id
           description: primary key
           tests:
              - unique
              - not_null    
    - name: product
      identifier: raw_gz_product
      description: product of Greenweez 
      columns:
        - name: products_id
          description: product_id
          tests:
            - unique
            - not_null

    - name: Facebook
      identifier: raw_gz_facebook
      description: Facebook ads of Greenweez 
  
    - name: Adwords
      identifier: raw_gz_adwords
      description: Adwords of Greenweez 
      
            
    - name: Criteo
      identifier: raw_gz_criteo
      description: Criteo of Greenweez 
     
    - name: Bing
      identifier: raw_gz_bing
      description: product of Greenweez 
         
models:
  - name: int_sales_margin
    description: joining sales and product to obtain pruchase cost and margin calcs
    columns:
      - name: orders_id
        description: order_id
        tests:
          - not_null
      - name: products_id
        description: products_id
      - name: date_date
        description: date of order
  - name: int_orders_margin
    description: margins by orders
    columns:
      - name: orders_id
        description: order_id
        tests:
          - unique
          - not_null
  - name: int_orders_operational
    description: orders to ship for op costs
    columns:
      - name: date_date
        description: date of orders
        tests: 
          - not_null
  - name: finance_days
    description: daily KPIs
    columns:
      - name: date_date
        description: date of orders
        tests: 
          - unique
          - not_null
      - name: nb_transactions
        description: number of transactions
      - name: total_revenue
        description: total rev calc
      - name: avg_basket
        description: averaging basket size, revn/order_num
      - name: operating_margin
        description: operating margin
      - name: total_purchase_cost
        description: sum of purchase cost
      - name: total_ship_fee
        description: sum of ship_fee
      - name: total_log_cost
        description: sum of log_cost
      - name: total_quantity
        description: sum of quantity
            
       
      
      


  
